name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable' # Keep channel stable for clarity, though version takes precedence

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./eenden_app

    - name: Build Web
      run: flutter build web --base-href /Eenden/
      working-directory: ./eenden_app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: eenden_app/build/web
