name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]  # Adjust if your default branch is named differently

permissions:
  contents: write  # Required for GITHUB_TOKEN to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ~/.flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./eenden_app

    - name: Build Flutter web
      run: flutter build web --base-href="/Eenden/"
      working-directory: ./eenden_app    

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: eenden_app/build/web
